# Generated by Django 4.1.7 on 2023-06-02 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postslab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
