# Generated by Django 4.1.7 on 2023-06-02 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postslab', '0002_rename_user_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
