# Generated by Django 4.1.7 on 2023-06-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postslab', '0003_rename_author_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_left', models.DateField(auto_now=True)),
            ],
        ),
    ]
